#service_account: ms-3-51@glb-ms-wgh-app-dev.iam.gserviceaccount.com
service_account: sa-wl-main@glb-ms-wgh-app-dev.iam.gserviceaccount.com

steps:
# Step-1 create image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/ms-3-51-flask', '.']
# Step-2 upload image in Artifactory
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/ms-3-51-flask']

# Step 3: Deploy to Cloud Run
- name: 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: 
  - 'run'
  - 'deploy'
  - 'ms-3-51-flask'  # Change this to your Cloud Run service name
  - '--image'
  - 'eu.gcr.io/$PROJECT_ID/ms-3-51-flask'
  - '--region'
  - 'europe-west3'  # Change to your region
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'  # Adjust based on your authentication needs
  - '--ingress'
  - 'internal'

options:
    logging: CLOUD_LOGGING_ONLY  # Do not store any logs
