service_account: gcp-devops-pro@hackathon-worldline.iam.gserviceaccount.com
#service_account: sa-wl-main@glb-ms-wgh-app-dev.iam.gserviceaccount.com
###  Artifact Registory path : us-docker.pkg.dev/hackathon-worldline/gcp-devops-proj

steps:
# Step-1 create image 
- name: 'us-docker.pkg.dev/hackathon-worldline/gcp-devops-proj/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/hackathon-worldline/gcp-devops-proj/ms-3-51-flask', '.']
# Step-2 upload image in Artifactory
- name: 'us-docker.pkg.dev/hackathon-worldline/gcp-devops-proj/docker'
  args: ['push', 'us-docker.pkg.dev/hackathon-worldline/gcp-devops-proj/ms-3-51-flask']

# Step 3: Deploy to Cloud Run
- name: 'us-docker.pkg.dev/hackathon-worldline/gcp-devops-proj/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: 
  - 'run'
  - 'deploy'
  - 'ms-3-51-flask'  # Change this to your Cloud Run service name
  - '--image'
  - 'us-docker.pkg.dev/hackathon-worldline/gcp-devops-proj/ms-3-51-flask'
  - '--region'
  - 'europe-west3'  # Change to your region
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'  # Adjust based on your authentication needs
  - '--ingress'
  - 'internal'

options:
    logging: CLOUD_LOGGING_ONLY  # Do not store any logs
